baseURL = 'https://bitwisemage.com/'
languageCode = 'en-us'
title = 'Bitwise Mage'
theme = 'hugo-monospace-web'
copyright = '© 2025 bitwisemage.com'
themeFoundationColors = 'gruvbox'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[taxonomies]
  tag = 'tags'

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
