baseURL = 'https://bitwisemage.com/'
languageCode = 'en-us'
title = 'Bitwise Mage'
theme = 'hugo-monospace-web'
copyright = '© 2025 bitwisemage.com'
themeFoundationColors = 'gruvbox'
enableRobotsTXT = true

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/BitwiseMage"

[[params.social]]
name = "X"
icon = "x"
url = "https://x.com/BitwiseMage"

[params]
TwitterUsername = "@bitwisemage"
TwitterImage = "bitwisemage.png"

[taxonomies]
  tag = 'tags'

[services]
  [services.googleAnalytics]
    id = 'G-P25726Q4PG'

[privacy]
  [privacy.googleAnalytics]
    disable = false
    respectDoNotTrack = true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = false
    tabWidth = 4
    wrapperClass = 'highlight'

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
