name = 'The Monospace Web - Hugo Edition'
license = 'MIT'
licenselink = ''
description = 'Theme based on The Monospace Web by Oskar Wickström (wickstrom.tech)'

# The home page of the theme, where the source can be found
homepage = ''

# If you have a running demo of the theme
demosite = ''

# Taxonomy terms
tags = ['blog', 'simple', 'minimal', 'responsive']
features = ['some', 'awesome', 'features']

# If the theme has a single author
[author]
  name = 'Bitwise Mage'
  homepage = 'https://bitwisemage.com/'
